apiVersion: v1
kind: Service
metadata:
  name: abstergo-webstore-service
  namespace: default
spec:
  selector:
    app: abstergo-webstore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Or ClusterIP, NodePort depending on your Minikube setup
